# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DesireLines
                                 A QGIS plugin
 OD desire lines
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-13
        copyright            : (C) 2024 by Diego Camargo
        email                : dg.camargo@proton.me
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DesireLines class from file DesireLines.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .desirelines import DesireLines
    return DesireLines(iface)
