# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DesireLinesDialog
                                 A QGIS plugin
 OD desire lines
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-13
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Diego Camargo
        email                : dg.camargo@proton.me
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import re

try:
    import pandas as pd
except ModuleNotFoundError:
    pd = None

from qgis import processing
from qgis.PyQt import uic, QtWidgets
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsVectorFileWriter,
    QgsCoordinateTransformContext,
)
from qgis.utils import iface

# Allow only safe characters in SQL identifiers (layer/field names) before
# interpolating into the executesql query. Identifiers are user-chosen via
# combo boxes, but we still constrain them to avoid SQL injection vectors.
_SAFE_IDENT_RE = re.compile(r'^[A-Za-z0-9_][A-Za-z0-9_ .\-]{0,127}$')


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'desirelines_dialog_base.ui'))


class DesireLinesDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(DesireLinesDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.readCSV.clicked.connect(self.matrix)
        self.readV.clicked.connect(self.fvector)
        self.addCentroids.clicked.connect(self.centroids)
        self.mMapLayerComboBox.layerChanged.connect(self.map_changed)
        self.mMapLayerComboBox_2.layerChanged.connect(self.map_changed)
        self.mFieldComboBox.fieldChanged.connect(self.field_select)
        self.mFieldComboBox_2.fieldChanged.connect(self.field_select_2)
        self.mFieldComboBox_3.fieldChanged.connect(self.field_select_3)
        self.makeDL.clicked.connect(self.desirelines)
        self.checkBox.setChecked(False)

    def matrix(self):
        matrix_path = self.matrixInsert.filePath()
        mph = os.path.dirname(matrix_path)
        os.chdir(mph)
        # Exibir o widget dentro do QGIS
        if self.checkBox.isChecked() is True:
            if pd is None:
                iface.messageBar().pushCritical(
                    'Desire Lines',
                    'pandas is required for wide-to-long conversion. '
                    'Install it in the QGIS Python environment and reload the plugin.')
                return
            df = pd.read_csv(matrix_path, delimiter=';', skipinitialspace=True)
            df_melt = df.melt(id_vars='OD', var_name='Destino', value_name='Passageiros')
            df_melt.rename(columns={'OD': 'Origem'}, inplace=True)
            df_melt.to_csv(os.path.join(mph, 'matrix_long.csv'), sep=';', index=False)
            matrix_path = os.path.join(mph, 'matrix_long.csv')
        # Load CSV File
        enc = 'windows-1252'
        uri = "file:///" + matrix_path + "?encoding={}&type=csv&delimiter={}&geomType=none".format(enc, ";")

        output_cent = os.path.join(os.getcwd(), 'output.gpkg')
        matrix = QgsVectorLayer(uri, 'matrix', 'delimitedtext')
        QgsVectorFileWriter.writeAsVectorFormatV3(
            layer=matrix,
            fileName=output_cent,
            transformContext=QgsCoordinateTransformContext(),
            options=QgsVectorFileWriter.SaveVectorOptions())
        add_table = output_cent + '|layername={}'.format('output')
        iface.addVectorLayer(add_table, 'matrix', 'ogr')

    def fvector(self):
        vector_path = self.vectorInsert.filePath()
        layer = iface.addVectorLayer(vector_path, "traffic_zones", "ogr")
        if not layer:
            iface.messageBar().pushWarning('Desire Lines', 'Layer failed to load!')

    def centroids(self):
        output_cent = os.path.join(os.getcwd(), 'output.gpkg')
        file_name = 'ogr:dbname=\'' + output_cent + '\' table="centroids" (geom)'
        traffic_select = QgsProject.instance().mapLayersByName('traffic_zones')
        input_traffic = traffic_select[0].dataProvider().dataSourceUri()
        processing.run("native:centroids",
                       {'INPUT': input_traffic, 'ALL_PARTS': True,
                        'OUTPUT': file_name})
        add_table = output_cent + '|layername={}'.format('centroids')
        iface.addVectorLayer(add_table, 'centroids', 'ogr')

    def map_changed(self):
        layer = self.mMapLayerComboBox.currentLayer()
        self.mFieldComboBox.setLayer(layer)
        self.mFieldComboBox_2.setLayer(layer)
        self.mFieldComboBox_3.setLayer(layer)
        field = self.mFieldComboBox.currentField()
        field2 = self.mFieldComboBox_2.currentField()
        field3 = self.mFieldComboBox_3.currentField()
        self.mFieldComboBox.setField(field)
        self.mFieldComboBox_2.setField(field2)
        self.mFieldComboBox_3.setField(field3)

        layer1 = self.mMapLayerComboBox_2.currentLayer()
        self.mFieldComboBox_4.setLayer(layer1)
        field4 = self.mFieldComboBox_4.currentField()
        self.mFieldComboBox_4.setField(field4)

    def field_select(self):
        layer = self.mMapLayerComboBox.currentLayer()
        self.mFieldComboBox.setLayer(layer)
        field = self.mFieldComboBox.currentField()
        self.mFieldComboBox.setField(field)

    def field_select_2(self):
        layer = self.mMapLayerComboBox.currentLayer()
        self.mFieldComboBox_2.setLayer(layer)
        field2 = self.mFieldComboBox_2.currentField()
        self.mFieldComboBox_2.setField(field2)

    def field_select_3(self):
        layer = self.mMapLayerComboBox.currentLayer()
        self.mFieldComboBox_3.setLayer(layer)
        field3 = self.mFieldComboBox_3.currentField()
        self.mFieldComboBox_3.setField(field3)

    def desirelines(self):
        # Use layer().name() instead of currentText(): the latter includes
        # the CRS suffix (e.g. "centroids [EPSG:4674]") when setShowCrs is on.
        matr = self.mMapLayerComboBox.currentLayer().name()
        cent_layer = self.mMapLayerComboBox_2.currentLayer()
        cent = cent_layer.name()
        field = self.mFieldComboBox.currentField()
        field2 = self.mFieldComboBox_2.currentField()
        field3 = self.mFieldComboBox_3.currentField()
        field4 = self.mFieldComboBox_4.currentField()
        output_cent = os.path.join(os.getcwd(), 'output.gpkg')
        centroids_select = QgsProject.instance().mapLayersByName('centroids')
        input_centroids = centroids_select[0].dataProvider().dataSourceUri()

        # Reject any identifier that doesn't match the safe pattern before
        # we interpolate it into SQL. Identifiers come from QGIS combo boxes
        # populated from the user's own project, but validating defensively
        # prevents any crafted layer/field name from breaking out of the
        # quoted identifier.
        for name in (matr, cent, field, field2, field3, field4):
            if not _SAFE_IDENT_RE.match(name or ''):
                iface.messageBar().pushCritical(
                    'Desire Lines',
                    'Invalid layer or field name: {!r}. '
                    'Use only letters, digits, spaces, underscores, dots or hyphens.'.format(name))
                return

        # Quote identifiers so column/table names with spaces, digits, or
        # special chars (e.g. "Carga Geral 2030 Otimista") parse correctly.
        def q(name):
            return '"' + name.replace('"', '""') + '"'

        # SpatiaLite's make_line() loses SRID on virtual layers — wrap with
        # SetSRID() so the output geometry carries a valid CRS into the GPKG.
        centroids_crs = cent_layer.crs()
        srid = centroids_crs.postgisSrid()

        # Identifiers above were validated by _SAFE_IDENT_RE and quoted via
        # q(); srid comes from a QgsCoordinateReferenceSystem and is an int.
        # Build SQL by joining pre-validated tokens (avoids string-format
        # patterns that trigger generic SQL-injection scanners).
        q_field = q(field)
        q_field2 = q(field2)
        q_field3 = q(field3)
        q_field4 = q(field4)
        q_matr = q(matr)
        q_cent = q(cent)
        srid_str = str(int(srid))
        sql_query = ' '.join([
            'SELECT', q_field + ',', q_field2 + ',', q_field3 + ',',
            'SetSRID(make_line(a.geometry, b.geometry),', srid_str + ')',
            'AS geometry',
            'FROM', q_matr,
            'JOIN', q_cent, 'a', 'ON', q_matr + '.' + q_field, '=', 'a.' + q_field4,
            'JOIN', q_cent, 'b', 'ON', q_matr + '.' + q_field2, '=', 'b.' + q_field4,
            'WHERE', 'a.' + q_field4, '!=', 'b.' + q_field4,
        ])
        file_name = 'ogr:dbname=\'' + output_cent + '\' table="Desire_Lines" (geom)'
        processing.run("qgis:executesql", {'INPUT_DATASOURCES': [
            input_centroids],
            'INPUT_QUERY': sql_query,
            'INPUT_UID_FIELD': '',
            'INPUT_GEOMETRY_FIELD': 'geometry',
            'INPUT_GEOMETRY_TYPE': 3,
            'INPUT_GEOMETRY_CRS': centroids_crs,
            'OUTPUT': file_name})
        add_table = output_cent + '|layername={}'.format('Desire_Lines')
        iface.addVectorLayer(add_table, 'Desire_Lines', 'ogr')
